# -*- coding: utf-8 -*-
"""examen-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smEfYDKAY6EHZukeNF3yJDlzErK7f0_1
"""

from kanren.core import run
from kanren import Relation, facts, var
hijo = var()
sobrino = var()
nieto = var()
padre = Relation()
madre = Relation()
tio = Relation()
tia = Relation()
abuelo = Relation()
abuela = Relation()
#sobrina
facts(madre,("Pamela","Carolina"))
#yo
facts(padre,("Hugo","Adolfo"),("Hugo","Pamela"))
facts(madre,("Rosario","Adolfo"),("Rosario","Pamela"))
#tia luz
facts(tio,("Raul","Adolfo"),("Raul","Pamela"))
facts(tia,("Luzmila","Adolfo"),("Luzmila","Pamela"))
facts(padre,("Raul","Raul"),("Raul","Nicolas"),("Raul","Gustavo"))
facts(madre,("Luzmila","Raul"),("Luzmila","Nicolas"),("Luzmila","Gustavo"))
#tio edgar
facts(tio,("Edgar","Adolfo"),("Edgar","Pamela"))
facts(tia,("Faviola","Adolfo"),("Faviola","Pamela"))
facts(padre,("Edgar","Adrian"),("Edgar","Pricila"))
facts(madre,("Faviola","Adrian"),("Faviola","Pricila"))
#tio fernando
facts(tio,("Fernando","Adolfo"),("Fernando","Pamela"))
facts(tia,("Sonia","Adolfo"),("Sonia","Pamela"))
facts(padre,("Fernando","Mauricio"),("Fernando","Martin"),("Fernando","Fernando"))
facts(madre,("Sonia","Mauricio"),("Sonia","Martin"),("Sonia","Fernando"))
#abuelos
facts(abuelo,("Fernando","Adolfo"),("Fernando","Pamela"))
facts(abuela,("Alicia","Adolfo"),("Alicia","Pamela"))
facts(padre,("Fernando","Rosario"),("Fernando","Fernando"),("Fernando","Luzmila"),("Fernando","Edgar"))
facts(madre,("Alicia","Rosario"),("Alicia","Fernando"),("Alicia","Luzmila"),("Alicia","Edgar"))


print(padre.facts)
print(madre.facts)

print(run(1,hijo,padre(hijo,"Adolfo")))
print(run(10,hijo,padre("Hugo",hijo)))

print(run(10,sobrino,tia(sobrino,"Adolfo")))
print(run(10,sobrino,tio("Edgar",sobrino)))

print(run(10,nieto,abuela(nieto,"Adolfo")))
print(run(10,nieto,abuelo("Fernando",nieto)))