# -*- coding: utf-8 -*-
"""examen-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pylIX21hC1lWFK8QtIoxXBy25EkctmYv
"""

from pandas.core.indexers import length_of_indexer
from google.colab import drive
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing as pr
drive.mount('/content/drive')
archivo='/content/drive/MyDrive/354/colab.csv'
contenido = pd.read_csv(archivo)
matriz = pd.DataFrame(contenido, columns=["NA_Sales","EU_Sales","JP_Sales","Other_Sales","Global_Sales"])
m1 = np.array(matriz)
print(matriz)
# print(m1)
print("GRAFICANDO")

fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1]) 
bp = ax.boxplot(m1)   
plt.show()

print("ESTANDARIZACION Y ESCALACION")
scal = pr.StandardScaler().fit(matriz)
scal
print("MEDIA")
print(scal.mean_)

print("ESCALACION")
print(scal.scale_)

print("TRANSFORMANDO LA MATRIZ")
matriz2 = scal.transform(matriz)
print(matriz2)
print("Los datos escalados tienen media 0 y varianza 1")

print("GRAFICANDO ESCALACION")
fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1]) 
bp = ax.boxplot(matriz2)   
plt.show()

print("DISCRETIZACION")
from sklearn.preprocessing import KBinsDiscretizer
pr1 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy="uniform")
pre1 = pr1.fit_transform(m1)
print(pre1)

print("GRAFICANDO DISCRETIZACION")
fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1])
bp = ax.boxplot(pre1)   
plt.show()

print("ENCODE")
enc = pr.OrdinalEncoder()
# matriz2 = pd.DataFrame(contenido, columns=["Genre","Platform"])
matriz2 = pd.DataFrame(contenido, columns=["Genre"])
m2 = np.array(matriz2)
print(m2)
m3 = enc.fit_transform(m2)
print(m3)

print("GRAFICANDO ENCODE")
fig = plt.figure(figsize =(12, 3)) 
ax = fig.add_axes([0, 0, 1, 1])
plt.hist(m3, bins=12, rwidth=0.7)
plt.show()