# -*- coding: utf-8 -*-
"""examen-6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRivhh-GDIw98fHmqkHx0FDacYvbuKHq
"""

from google.colab import drive
import pandas as pd

drive.mount('/content/drive')
archivo='/content/drive/MyDrive/354/6fin.csv'
contenido = pd.read_csv(archivo)
from sklearn import tree
from sklearn import datasets
from IPython.display import display 

print("-----------CLASES-----------")
categoria = pd.DataFrame(contenido, columns=["Genre"])
display(categoria)

print("-----------DATOS-----------")
datos = pd.DataFrame(contenido, columns=["Global_Sales","Year"])
display(datos)
datos.rename(columns={"Global_Sales":'V',"Year":'A'},inplace=True)
display(datos)

print("-----------COLUMNAS DE DATOS-----------")
print(datos.columns)

print("-----------ONE HOT ENCODE A DATOS-----------")
data1 = pd.get_dummies(datos)
display(data1.columns)

print("-----------RENOMBRANDO COLUMNA DE DATOS-----------")
display(data1)

clasificador = tree.DecisionTreeClassifier()
datay = clasificador.fit(data1,categoria)

print("-----------TOMAMOS LOS PRIMEROS 3 VALORES DE LA DATA Y SE TRATARAN DE PREDECIR-----------")
prueba = [[0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0],
          [0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0],
          [0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0]]
display(prueba)
resultado = clasificador.predict(prueba)

print("-----------PREDICE-----------")
display(resultado)
display(categoria)