# -*- coding: utf-8 -*-
"""examen-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjHieeuj5ti-isYqG6GJl3pw7_FZTA2O
"""

from pandas.core.indexers import length_of_indexer
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np
drive.mount('/content/drive')
archivo='/content/drive/MyDrive/354/colab.csv'
import pandas as pd
contenido = pd.read_csv(archivo)
print(contenido)

print("EJERCICIO 1-a y b")
print("COLUMNA 1-PLATAFORMA-CONSOLA")
columna = contenido["Platform"]
#print(list(columna))
print(list(columna))
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
co=list(etiquetar.classes_)
print(co)

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
plt.figure(figsize=(20,5))
plt.hist(list(columna), bins=31, rwidth=0.7)
plt.show()
#import seaborn as sns
#import matplotlib.pyplot as plt

#plt.boxplot(columna1)
#plt.show()
#plt.hist(columna1)
#plt.show()
#tgraf= columna1.sum(axis=1)
#plt.bar(columna1)
#plt.bar(lista,columna1)
#plt.show()

#ax.bar()

print("EJERCICIO 1-a y b")
print("COLUMNA 2-YEAR (año de salida del video juego)")
columna = contenido["Year"]
#print(list(columna))
print(list(columna))
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
plt.figure(figsize=(20,5))
plt.hist(list(columna), bins=40, rwidth=0.7)
plt.show()

print("EJERCICIO 1-a y b")
print("COLUMNA 3-GENRE (genero del video juego)")
columna = contenido["Genre"]
print(list(columna))
#print(columna)
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
plt.figure(figsize=(20,5))
plt.hist(list(columna), bins=12, rwidth=0.7)
plt.show()

print("EJERCICIO 1-a y b")
print("COLUMNA 4-Publisher (empresa que publica el juego)")
columna = contenido["Publisher"]
print(list(columna))
# print(columna)
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
plt.figure(figsize=(20,5))
plt.hist(list(columna), bins=578, rwidth=0.7)
plt.show()

print("EJERCICIO 1-a y b")
print("COLUMNA 5-NA_Sales (ventas en Norte America)")
columna = contenido["NA_Sales"]
print(list(columna))
#print(columna)
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1]) 
bp = ax.boxplot(columna1)   
plt.show()

print("EJERCICIO 1-a y b")
print("COLUMNA 6-EU_Sales (ventas en Europa)")
columna = contenido["EU_Sales"]
print(list(columna))
# print(columna)
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1]) 
bp = ax.boxplot(columna1)   
plt.show()

print("EJERCICIO 1-a y b")
print("COLUMNA 7-JP_Sales (ventas en japon)")
columna = contenido["JP_Sales"]
print(list(columna))
# print(columna)
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1]) 
bp = ax.boxplot(columna1)   
plt.show()

print("EJERCICIO 1-a y b")
print("COLUMNA 8-Other_Sales (venta en otros paises)")
columna = contenido["Other_Sales"]
print(list(columna))
# print(columna)
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1]) 
bp = ax.boxplot(columna1)   
plt.show()

print("EJERCICIO 1-a y b")
print("COLUMNA 9-Global_Sales (ventas totales)")
columna = contenido["Global_Sales"]
print(list(columna))
# print(columna)
from sklearn import preprocessing
etiquetar = preprocessing.LabelEncoder()
etiquetar.fit(columna)
etiquetar.classes_
print("LAS CLASES SON:")
etiquetar.classes_
print(list(etiquetar.classes_))

print("EQUIVALEN:")
es = etiquetar.classes_
ind = len(es)
lista=[]
for i in range(ind):
  lista.append(i)
print(lista)

print("CON LABEL ENCODE")
# cod = etiquetar.transform(columna)
print(etiquetar.transform(columna))
columna1 = etiquetar.transform(columna)

##usamos metodos sort()
print("ORDENANDO")
columna1.sort()
#print(list(columna1))
print(columna1)
## print(columna1)
#perc = int(input('introdusca percentil: '))
calcu = round((25*len(columna))/100)
print("El percentil 25 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((90*len(columna))/100)
print("El percentil 90 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])
calcu = round((95*len(columna))/100)
print("El percentil 95 se encuentra en la posicion:",calcu,", este apunta a la etiqueta:",columna1[round(calcu)],", y representa:",list(etiquetar.classes_)[columna1[calcu]])


array = np.array(columna1)
print("PERCENTIL CON NUMPY")
print("percentil con numpy 25 =", np.percentile(array,25))
print("percentil con numpy 90 =", np.percentile(array,90))
print("percentil con numpy 95 =", np.percentile(array,95))

print("GRAFICANDO")
fig = plt.figure(figsize =(5, 3)) 
ax = fig.add_axes([0, 0, 1, 1]) 
bp = ax.boxplot(columna1)   
plt.show()